# Generated by Django 2.1.5 on 2019-02-18 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yaris', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='kurallar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kural', models.IntegerField()),
                ('aciklama', models.TextField()),
            ],
            options={
                'verbose_name': 'Kural',
                'verbose_name_plural': 'Kurallar',
            },
        ),
    ]
