# Generated by Django 2.1.5 on 2019-02-21 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yaris', '0002_kurallar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='katilimci',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-posta'),
        ),
        migrations.AlterField(
            model_name='katilimci',
            name='lastname',
            field=models.CharField(blank=True, max_length=60, verbose_name='Soyadı'),
        ),
        migrations.AlterField(
            model_name='katilimci',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, verbose_name='Cep Telefonu'),
        ),
        migrations.AlterField(
            model_name='katilimci',
            name='name',
            field=models.CharField(blank=True, max_length=60, verbose_name='Adı'),
        ),
        migrations.AlterField(
            model_name='katilimci',
            name='username',
            field=models.CharField(blank=True, max_length=120, verbose_name='Takma isim'),
        ),
    ]
