# Generated by Django 2.1.5 on 2019-02-21 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yaris', '0003_auto_20190222_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pigeon',
            name='ucret',
            field=models.IntegerField(default=0, verbose_name='Alıncan Ücret'),
        ),
    ]
