# Generated by Django 2.1.5 on 2019-02-21 22:30

from django.db import migrations, models
import yaris.models


class Migration(migrations.Migration):

    dependencies = [
        ('yaris', '0004_auto_20190222_0006'),
    ]

    operations = [
        migrations.CreateModel(
            name='sponsorlar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sponsor', models.CharField(max_length=120, verbose_name='Sponsor')),
                ('logo', models.ImageField(upload_to=yaris.models.logos)),
            ],
        ),
    ]
