# Generated by Django 2.1.5 on 2019-02-22 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yaris', '0005_sponsorlar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sponsorlar',
            options={'verbose_name': 'Sponsor', 'verbose_name_plural': 'Sponsorlar'},
        ),
        migrations.AddField(
            model_name='temsilci',
            name='facebook',
            field=models.CharField(blank=True, max_length=150, verbose_name='Facebook Adresi'),
        ),
    ]
