# Generated by Django 2.1.5 on 2019-02-24 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='iletisim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adi', models.CharField(max_length=60, verbose_name='Adı')),
                ('soyadi', models.CharField(max_length=60, verbose_name='Soyadi')),
                ('tel', models.CharField(max_length=20, verbose_name='Telefon')),
                ('email', models.EmailField(max_length=254, verbose_name='E-posta')),
                ('mesaj', models.TextField(verbose_name='Mesaj')),
            ],
            options={
                'verbose_name_plural': 'İletişim',
            },
        ),
    ]
