# Generated by Django 2.1.5 on 2019-02-28 14:32

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('galeri', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galeri',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to='kumes'),
        ),
    ]
