# Generated by Django 2.1.5 on 2019-02-28 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeri', '0002_auto_20190228_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galeri',
            name='image',
            field=models.ImageField(upload_to='kumes'),
        ),
    ]
