# Generated by Django 2.1.5 on 2019-02-28 14:57

from django.db import migrations, models
import galeri.models


class Migration(migrations.Migration):

    dependencies = [
        ('galeri', '0003_auto_20190228_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galeri',
            name='image',
            field=models.ImageField(upload_to=galeri.models.get_file_path),
        ),
    ]
